project("ctemplate" C)
include(GNUInstallDirs)

install(DIRECTORY man1/ DESTINATION ${CMAKE_INSTALL_MANDIR}/man1
  FILES_MATCHING PATTERN "*.1")

install(DIRECTORY man2/ DESTINATION ${CMAKE_INSTALL_MANDIR}/man2
  FILES_MATCHING PATTERN "*.2")

install(DIRECTORY man3/ DESTINATION ${CMAKE_INSTALL_MANDIR}/man3
  FILES_MATCHING PATTERN "*.3")

install(DIRECTORY man4/ DESTINATION ${CMAKE_INSTALL_MANDIR}/man4
  FILES_MATCHING PATTERN "*.4")

install(DIRECTORY man5/ DESTINATION ${CMAKE_INSTALL_MANDIR}/man5
  FILES_MATCHING PATTERN "*.5")

install(DIRECTORY man6/ DESTINATION ${CMAKE_INSTALL_MANDIR}/man6
  FILES_MATCHING PATTERN "*.6")

install(DIRECTORY man7/ DESTINATION ${CMAKE_INSTALL_MANDIR}/man7
  FILES_MATCHING PATTERN "*.7")

install(DIRECTORY man8/ DESTINATION ${CMAKE_INSTALL_MANDIR}/man8
  FILES_MATCHING PATTERN "*.8")
